services:
  stats-server:
    build: stat-service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
